# Generated by Django 4.0.3 on 2022-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('uri', models.CharField(max_length=200, unique=True)),
                ('result', models.JSONField()),
                ('cAt', models.FloatField()),
                ('uAt', models.FloatField()),
            ],
        ),
    ]
