# Generated by Django 4.0.3 on 2022-03-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_recognition_uri'),
        ('uauth', '0001_initial'),
        ('userUploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUpload',
            new_name='UserUploads',
        ),
    ]
