# Generated by Django 4.0.3 on 2022-03-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0001_initial'),
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('recid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.recognition')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uauth.user')),
            ],
        ),
    ]
