name: BOCR CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - uses: shogo82148/actions-setup-mysql@v1
      with:
          mysql-version: '8.0'
          auto-start: true
          
          
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Initiate MySQL
      run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE bocr'
      
    - name: Migrate database
      run: |
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Run Tests
      run: |
        python manage.py test
